server:
  port: 6688


grpc:
  client:
    helloWorld-grpc-server:
      address: 'static://127.0.0.1:8888'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext